#!/usr/bin/env node

// ============================================================================
// Follow Builders — Prepare Digest
// ============================================================================
// Gathers everything the LLM needs to produce a digest:
// - Fetches the central feeds (tweets + podcasts)
// - Fetches the latest prompts from GitHub
// - Reads the user's config (language, delivery method)
// - Outputs a single JSON blob to stdout
//
// The LLM's ONLY job is to read this JSON, remix the content, and output
// the digest text. Everything else is handled here deterministically.
//
// Usage: node prepare-digest.js
// Output: JSON to stdout
// ============================================================================

import { readFile, mkdir } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

// -- Constants ---------------------------------------------------------------

const USER_DIR = join(homedir(), '.follow-builders');
const CONFIG_PATH = join(USER_DIR, 'config.json');

// HYBRID SOURCING:
// - X tweets + podcasts come from the UPSTREAM central feed (zarazhangrui),
//   generated daily with the maintainer's paid X + pod2txt keys. This keeps
//   the 26 builders + 6 podcasts free, with no keys of our own.
// - Blogs (incl. the pi.website blog) + YouTube channels come from OUR fork
//   (yuxuehui), generated by our own GitHub Action using only the free Supadata key.
const FEED_X_URL = 'https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-x.json';
const FEED_PODCASTS_URL = 'https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-podcasts.json';
const FEED_BLOGS_URL = 'https://raw.githubusercontent.com/yuxuehui/follow-builders/main/feed-blogs.json';
const FEED_YOUTUBE_URL = 'https://raw.githubusercontent.com/yuxuehui/follow-builders/main/feed-youtube.json';

const PROMPTS_BASE = 'https://raw.githubusercontent.com/yuxuehui/follow-builders/main/prompts';
const PROMPT_FILES = [
  'summarize-podcast.md',
  'summarize-tweets.md',
  'summarize-blogs.md',
  'summarize-youtube.md',
  'digest-intro.md',
  'translate.md'
];

// -- Fetch helpers -----------------------------------------------------------

async function fetchJSON(url) {
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.json();
}

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) return null;
  return res.text();
}

// -- Dedup / exclusions ------------------------------------------------------

// Builders to exclude from the X feed. The X source list lives upstream and
// can't be edited there, so we filter unwanted handles here. Lowercase.
const EXCLUDED_X_HANDLES = new Set(['zarazhangrui']);

// The blogs + youtube feeds are regenerated by our GitHub Action once a day and
// persist on disk between runs. To avoid re-posting the same items when the
// digest runs more than once per generation (a manual re-run, or a day the
// Action didn't refresh the feed), only include them if their feed was
// generated within the last FRESH_HOURS. The Action runs ~2h before delivery,
// so 8h gives ample slack while still treating yesterday's feed as stale.
const FRESH_HOURS = 8;

function feedAgeHours(feed) {
  if (!feed?.generatedAt) return Infinity;
  return (Date.now() - new Date(feed.generatedAt).getTime()) / 36e5;
}

// -- Main --------------------------------------------------------------------

async function main() {
  const errors = [];

  // 1. Read user config
  let config = {
    language: 'en',
    frequency: 'daily',
    delivery: { method: 'stdout' }
  };
  if (existsSync(CONFIG_PATH)) {
    try {
      config = JSON.parse(await readFile(CONFIG_PATH, 'utf-8'));
    } catch (err) {
      errors.push(`Could not read config: ${err.message}`);
    }
  }

  // 2. Fetch all feeds (X + podcasts from upstream, blogs + youtube from fork)
  const [feedX, feedPodcasts, feedBlogs, feedYoutube] = await Promise.all([
    fetchJSON(FEED_X_URL),
    fetchJSON(FEED_PODCASTS_URL),
    fetchJSON(FEED_BLOGS_URL),
    fetchJSON(FEED_YOUTUBE_URL)
  ]);

  if (!feedX) errors.push('Could not fetch tweet feed');
  if (!feedPodcasts) errors.push('Could not fetch podcast feed');
  if (!feedBlogs) errors.push('Could not fetch blog feed');
  if (!feedYoutube) errors.push('Could not fetch youtube feed');
  if (feedX?.errors?.length) {
    errors.push(
      ...feedX.errors.map((error) => `Tweet feed problem: ${error}`)
    );
  }
  if (feedPodcasts?.errors?.length) {
    errors.push(
      ...feedPodcasts.errors.map((error) => `Podcast feed problem: ${error}`)
    );
  }
  if (feedBlogs?.errors?.length) {
    errors.push(
      ...feedBlogs.errors.map((error) => `Blog feed problem: ${error}`)
    );
  }
  if (feedYoutube?.errors?.length) {
    errors.push(
      ...feedYoutube.errors.map((error) => `YouTube feed problem: ${error}`)
    );
  }

  // 3. Load prompts with priority: user custom > remote (GitHub) > local default
  //
  // If the user has a custom prompt at ~/.follow-builders/prompts/<file>,
  // use that (they personalized it — don't overwrite with remote updates).
  // Otherwise, fetch the latest from GitHub so they get central improvements.
  // If GitHub is unreachable, fall back to the local copy shipped with the skill.
  const prompts = {};
  const scriptDir = decodeURIComponent(new URL('.', import.meta.url).pathname);
  const localPromptsDir = join(scriptDir, '..', 'prompts');
  const userPromptsDir = join(USER_DIR, 'prompts');

  for (const filename of PROMPT_FILES) {
    const key = filename.replace('.md', '').replace(/-/g, '_');
    const userPath = join(userPromptsDir, filename);
    const localPath = join(localPromptsDir, filename);

    // Priority 1: user's custom prompt (they personalized it)
    if (existsSync(userPath)) {
      prompts[key] = await readFile(userPath, 'utf-8');
      continue;
    }

    // Priority 2: latest from GitHub (central updates)
    const remote = await fetchText(`${PROMPTS_BASE}/${filename}`);
    if (remote) {
      prompts[key] = remote;
      continue;
    }

    // Priority 3: local copy shipped with the skill
    if (existsSync(localPath)) {
      prompts[key] = await readFile(localPath, 'utf-8');
    } else {
      errors.push(`Could not load prompt: ${filename}`);
    }
  }

  // 3b. Filter + dedup before building the output.
  // - Drop excluded builders from the X feed.
  // - Gate the fork-generated blogs + youtube feeds on freshness so a single
  //   feed generation is delivered at most once (prevents repeats on re-runs
  //   or on a day the Action didn't refresh the feed).
  const x = (feedX?.x || []).filter(
    (b) => !EXCLUDED_X_HANDLES.has((b.handle || '').toLowerCase())
  );
  const youtubeStale = feedAgeHours(feedYoutube) > FRESH_HOURS;
  const blogsStale = feedAgeHours(feedBlogs) > FRESH_HOURS;
  const youtube = youtubeStale ? [] : (feedYoutube?.youtube || []);
  const blogs = blogsStale ? [] : (feedBlogs?.blogs || []);
  if (youtubeStale && feedYoutube?.youtube?.length) {
    errors.push('YouTube feed is stale (already delivered) — skipping to avoid duplicates');
  }
  if (blogsStale && feedBlogs?.blogs?.length) {
    errors.push('Blog feed is stale (already delivered) — skipping to avoid duplicates');
  }

  // 4. Build the output — everything the LLM needs in one blob
  const output = {
    status: 'ok',
    generatedAt: new Date().toISOString(),

    // User preferences
    config: {
      language: config.language || 'en',
      frequency: config.frequency || 'daily',
      delivery: config.delivery || { method: 'stdout' }
    },

    // Content to remix
    podcasts: feedPodcasts?.podcasts || [],
    x,
    blogs,
    youtube,

    // Stats for the LLM to reference
    stats: {
      podcastEpisodes: feedPodcasts?.podcasts?.length || 0,
      xBuilders: x.length,
      totalTweets: x.reduce((sum, a) => sum + a.tweets.length, 0),
      blogPosts: blogs.length,
      youtubeVideos: youtube.length,
      feedGeneratedAt: feedX?.generatedAt || feedPodcasts?.generatedAt || feedBlogs?.generatedAt || null
    },

    // Prompts — the LLM reads these and follows the instructions
    prompts,

    // Non-fatal errors
    errors: errors.length > 0 ? errors : undefined
  };

  console.log(JSON.stringify(output, null, 2));
}

main().catch(err => {
  console.error(JSON.stringify({
    status: 'error',
    message: err.message
  }));
  process.exit(1);
});
